### ISSUE TITLE
Build against Numpy 1.13

### ISSUE THREAD

**Issue by alimanfoo** [conda-forge/bcolz-feedstock#3]

**Comment by jakirkham** [comment]
Normally would say re-render to do this, though we are actually changing [how one builds against NumPy]( https://conda-forge.org/docs/meta.html#building-against-numpy ). So would take a look at that and update accordingly.

**Comment by alimanfoo** [comment]
resolved via https://github.com/conda-forge/bcolz-feedstock/pull/8
