### ISSUE TITLE
Re-render now the NumPy reqs changed

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/bcolz-feedstock#6]
@conda-forge-admin, please rerender.

xref: https://github.com/conda-forge/bcolz-feedstock/pull/5

**Comment by jakirkham** [comment]
Forgot that we haven't taught the bot this yet. Will leave it open as a task for now.

**Comment by alimanfoo** [comment]
resolved via https://github.com/conda-forge/bcolz-feedstock/pull/8
