### ISSUE TITLE
Illegal instruction issue with bcolz

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/bcolz-feedstock#7]
Recently ran into an issue in the Dask CI where `bcolz` triggered a crash due to an illegal instruction. Not having much more to go on, guessing it was an AVX2 instruction (think Travis CI can handle AVX). As there was a recent build and we are using `conda-forge` wondering if something changed in `bcolz` (either upstream or about the build) and if there is a way to rebuild it possibly with these instructions disabled (or some other solution). Thoughts?

cc @mrocklin

ref: https://travis-ci.org/dask/dask/jobs/368705236#L3792

**Comment by alimanfoo** [comment]
Looks like bcolz setup.py looks for a "DISABLE_BCOLZ_AVX2" environment variable, could use this to ensure building without avx2.

**Comment by alimanfoo** [comment]
I'll make a PR...

**Comment by jakirkham** [comment]
Yep, that fixed it. Thanks @alimanfoo. :)

ref: https://travis-ci.org/dask/dask/builds/369157404 (the one failure is ours so not related to this)
